In [2]:
import numpy as np

In [ ]:
arr1 = np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [ ]:
alpha_arr = ["q", "y"]
np.array(alpha_arr)

array(['q', 'y'], dtype='<U1')

In [ ]:
for i in range(1,6):
  print(i)

1
2
3
4
5


In [ ]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [ ]:
n = np.arange(0,100,2)
print(n)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [ ]:
n = np.arange(100,0,-2)
print(n)

[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2]


In [ ]:
x = np.linspace(1,5)
x

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [ ]:
x = np.linspace(0,1,5)
x

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
n = np.random.randint(1,100,5)
n

array([33, 27, 10,  5,  4])

In [ ]:
k = np.random.rand(1,10,2)
k

array([[[0.31332668, 0.6062849 ],
        [0.15619758, 0.96402791],
        [0.16902156, 0.59927439],
        [0.10218621, 0.71952198],
        [0.68700104, 0.40838005],
        [0.02759266, 0.385914  ],
        [0.10498219, 0.45497431],
        [0.47417201, 0.58785564],
        [0.35149952, 0.01903413],
        [0.00543789, 0.91772271]]])

In [1]:
# Saturday topics

In [3]:
# 1D Array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [4]:
# 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [6]:
# 3D Array
arr3 = np.array([[1,2,3], [1,2,3],[1,2,3]])
print(arr3)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [7]:
# linspace() NumPy ka ek function hai jo equal spacing ke sath numbers ka array banata hai.
# Isme aap start point, end point, aur kitne numbers chahiye specify karte ho.
# np.linspace(start, stop, num=50)

arr = np.linspace(0, 10, 5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [12]:
arr = np.linspace(0, 100, 2)
print(arr)

[  0. 100.]


In [16]:
arr = np.linspace(1, 100)
print(arr)

[  1.           3.02040816   5.04081633   7.06122449   9.08163265
  11.10204082  13.12244898  15.14285714  17.16326531  19.18367347
  21.20408163  23.2244898   25.24489796  27.26530612  29.28571429
  31.30612245  33.32653061  35.34693878  37.36734694  39.3877551
  41.40816327  43.42857143  45.44897959  47.46938776  49.48979592
  51.51020408  53.53061224  55.55102041  57.57142857  59.59183673
  61.6122449   63.63265306  65.65306122  67.67346939  69.69387755
  71.71428571  73.73469388  75.75510204  77.7755102   79.79591837
  81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]


In [19]:
arr = np.linspace(0, 10, 15)   # ab 15 numbers generate kiye
reshaped = arr.reshape(3,5)
print(reshaped)

[[ 0.          0.71428571  1.42857143  2.14285714  2.85714286]
 [ 3.57142857  4.28571429  5.          5.71428571  6.42857143]
 [ 7.14285714  7.85714286  8.57142857  9.28571429 10.        ]]


In [20]:
# np.eye() ek NumPy function hai jo identity matrix banata hai.
# Identity matrix ek square matrix hota hai jisme diagonal par 1 hote hain aur baaki jagah 0.

arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
# np.shape() Ye NumPy ka function hai jo array ka size aur dimension (rows × columns × …) batata hai.
# Iska output ek tuple hota hai.

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.shape(arr))

(2, 3)


In [22]:
arr3 = np.array([ [[1,2],[3,4]], [[5,6],[7,8]] ])
print(arr3.shape)

(2, 2, 2)
